# serverless.yml

# IMPORTANT!
# Change iamRoleStatements resource to your DynamoDB ARN. This is an overly broad permission.

service: askJames-caffeine

package:
  exclude:
    - data/*
    - local/*

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  memorySize: 1024
  region: us-east-1
  timeout: 15
  versionFunctions: false  
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:*
    Resource:
      - "*"

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
        